### ISSUE TITLE
get those parameters from the requests

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/GraphQLWFS#18]

**Comment by jrajak10** [comment]
Working on error validation

**Comment by abellj01** [comment]
The function accepts three parameters:
count, typenames, filter which include property and propertyvalue

**Comment by abellj01** [comment]
The following link: https://us-central1-gcp-training-144309.cloudfunctions.net/graphqlwfs?count=5&propertyName=ward&provertyvalue=Bottinsham%20ward, works having been tested as shown.

**Comment by sebastianovide** [comment]
ok, we'll implement error validation in the GraphQL ticket
