### ISSUE TITLE
replace boundaries _lines with topographyTopographicArea

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/GraphQLWFS#98]
as  boundaries _lines is not supported anymore, need to migrate to the new product. Which one ? Zoomstack_Boundaries supports only polygons

**Comment by sebastianovide** [comment]
```
 # {
    #      topographyTopographicArea(
    #         first: 5,
    #         theme: "Buildings",
    #         reasonForChange: "Restructured"
    #     )
    # }
```

**Comment by mysticetii** [comment]
{
          topographyTopographicArea(
             first: 5,
             toid: "osgb1000000000006",
             featureCode: 10021,
             theme: "Buildings",
             CalculatedAreaValue: 46.68,
             reasonForChange: "Restructured",
             descriptiveGroup: "Building",
             make: "Manmade",
             physicalLevel: 50,
         )
     }
